name: course_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  flutter_rating_bar: ^4.0.1
  flex_color_scheme: ^7.0.5
  url_launcher: ^6.1.11
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  crypto: ^3.0.3
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true